POST http://localhost:4000/api/products
Content-Type: application/json

[
  {
    "_id": "65678157776eddc6c35c06ee",
    "category": 1,
    "subcategory": 1,
    "productName": "PowerCharge Pro",
    "manufacturer": "ElectraTech",
    "country": "USA",
    "price": 149.99,
    "description": "Experience the cutting-edge PowerCharge Pro, a versatile 8A-32A 3KW 7KW portable EV charger crafted for electric car enthusiasts. Engineered by ElectraTech, this mobile charging station ensures seamless and efficient charging for your EV's battery.",
    "img": "./images/products/charger2.jpg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "65678157776eddc6c35c06f0",
    "category": 1,
    "subcategory": 1,
    "productName": "EcoCharge Pro",
    "manufacturer": "GreenPower Tech",
    "country": "USA",
    "price": 249.99,
    "description": "Introducing the EcoCharge Pro, a cutting-edge 8A-32A 3KW 7KW portable EV charger designed for electric car enthusiasts. Experience seamless and efficient mobile charging with this advanced charging station. Equipped with state-of-the-art technology, it ensures optimal performance for your EV's battery.",
    "img": "./images/products/charger3.jpg",
    "discount": 0.3,
    "__v": 0
  },
  {
    "_id": "65678157776eddc6c35c06f2",
    "category": 1,
    "subcategory": 1,
    "productName": "EcoCharge Max",
    "manufacturer": "GreenTech Innovations",
    "country": "China",
    "price": 349.99,
    "description": "Introducing the EcoCharge Max, a powerful 8A-32A 3KW 7KW portable EV charger designed for electric car enthusiasts. Manufactured by GreenTech Innovations in China, this cutting-edge mobile charging station ensures efficient charging for your EV's battery.",
    "img": "./images/products/charger4.jpg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "65678157776eddc6c35c06f4",
    "category": 1,
    "subcategory": 1,
    "productName": "TurboVolt X",
    "manufacturer": "QuantumCharge Tech",
    "country": "China",
    "price": 449.99,
    "description": "Unleash the power of the TurboVolt X, an advanced 8A-32A 3KW 7KW portable EV charger crafted by QuantumCharge Tech. This state-of-the-art mobile charging station, proudly manufactured in China, is designed to provide rapid and efficient charging for electric car batteries on the go.",
    "img": "./images/products/charger5.jpg",
    "discount": 0.9,
    "__v": 0
  },
  {
    "_id": "65678157776eddc6c35c06f6",
    "category": 1,
    "subcategory": 1,
    "productName": "EcoBoost Elite",
    "manufacturer": "GreenDrive Solutions",
    "country": "China",
    "price": 459.99,
    "description": "Discover the EcoBoost Elite, an innovative 8A-32A 3KW 7KW portable EV charger engineered by GreenDrive Solutions. Manufactured in China, this cutting-edge mobile charging station is tailored for efficient and on-the-go charging of electric car batteries.",
    "img": "./images/products/charger6.jpg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "65678157776eddc6c35c06f8",
    "category": 1,
    "subcategory": 1,
    "productName": "PowerFlow X1",
    "manufacturer": "EcoCharge Dynamics",
    "country": "China",
    "price": 459.99,
    "description": "Introducing the PowerFlow X1, a revolutionary 8A-32A 3KW 7KW portable EV charger designed by EcoCharge Dynamics. Crafted in China, this dynamic mobile charging station provides seamless and efficient charging for electric vehicles, ensuring you stay powered up wherever your journey takes you.",
    "img": "./images/products/charger7.jpg",
    "discount": 0.7,
    "__v": 0
  },
  {
    "_id": "65678157776eddc6c35c06fa",
    "category": 1,
    "subcategory": 1,
    "productName": "Charger Power Simple",
    "manufacturer": "Chinzel",
    "country": "China",
    "price": 400,
    "description": "8A-32A 3KW 7KW Portable ev charger for ev electric car battery mobile charging station",
    "img": "./images/products/Charger.jpeg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "65678157776eddc6c35c06fc",
    "category": 1,
    "subcategory": 1,
    "productName": "TeslaCharge Compact",
    "manufacturer": "Tesla",
    "country": "China",
    "price": 239.99,
    "description": "Introducing the TeslaCharge Compact, a sleek 8A-32A 3KW 7KW portable EV charger by Tesla. Crafted in China, this compact and efficient mobile charging station ensures a seamless charging experience for electric vehicles, providing reliable power on the go.",
    "img": "./images/products/charger8.jpg",
    "discount": 0.5,
    "__v": 0
  },
  {
    "_id": "65678157776eddc6c35c070c",
    "category": 2,
    "subcategory": 1,
    "productName": "SolarX Pro 2",
    "manufacturer": "Solar Tech Innovations",
    "country": "China",
    "price": 349.99,
    "description": "Experience the SolarX Pro, a high-efficiency solar panel designed for both residential and commercial use. Engineered by Solar Tech Innovations, this cutting-edge panel maximizes energy production for a sustainable future.",
    "img": "./images/products/solar-panel-1.jpeg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "65678157776eddc6c35c070e",
    "category": 2,
    "subcategory": 1,
    "productName": "SolarX Pro",
    "manufacturer": "Sunergy",
    "country": "USA",
    "price": 399.99,
    "description": "Experience the SolarX Pro, a premium solar panel featuring advanced photovoltaic technology for maximum energy efficiency.",
    "img": "./images/products/mono.jpg",
    "discount": 0.2,
    "__v": 0
  },
  {
    "_id": "65678157776eddc6c35c0710",
    "category": 2,
    "subcategory": 1,
    "productName": "EcoSolar Elite",
    "manufacturer": "GreenEco",
    "country": "Germany",
    "price": 449.99,
    "description": "Discover the EcoSolar Elite, an eco-friendly solar panel designed for sustainable energy production.",
    "img": "./images/products/polycrystalline_solar_panel.jpg",
    "discount": 0.1,
    "__v": 0
  },
  {
    "_id": "65678157776eddc6c35c0712",
    "category": 2,
    "subcategory": 1,
    "productName": "SolarPro X",
    "manufacturer": "Solar Power Inc.",
    "country": "China",
    "price": 329.99,
    "description": "Introducing the SolarPro X, a high-efficiency solar panel designed for both residential and commercial use.",
    "img": "./images/products/solar-panel2.jpg",
    "discount": 0.15,
    "__v": 0
  },
  {
    "_id": "65678157776eddc6c35c072a",
    "category": 3,
    "subcategory": 1,
    "productName": "EcoPower Hub",
    "manufacturer": "EcoInnovate",
    "country": "Australia",
    "price": 1499.99,
    "description": "Upgrade to the EcoPower Hub, an energy-efficient home battery pack designed for sustainable living. With a capacity of 15.2 kWh, it is suitable for powering energy-efficient refrigerators and other household appliances.",
    "img": "./images/products/home2.jpg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "65678157776eddc6c35c072c",
    "category": 3,
    "subcategory": 1,
    "productName": "xComet Pack",
    "manufacturer": "ABB",
    "country": "Finland",
    "price": 533,
    "description": "Powerporter 11.0 Energy Capacity: 19.6kW with insane power output going to the moon and backwards.",
    "img": "./images/products/home-battery-pack.jpeg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "65678157776eddc6c35c072e",
    "category": 3,
    "subcategory": 1,
    "productName": "EcoEnergy Pro",
    "manufacturer": "ABB",
    "country": "Finland",
    "price": 1199.99,
    "description": "Introducing the EcoEnergy Pro, a cutting-edge battery pack by ABB. With a remarkable energy capacity of 22.6 kWh, the Powerporter 11.0 is designed to meet your energy storage needs efficiently.",
    "img": "./images/products/home3.jpg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "65678157776eddc6c35c0730",
    "category": 4,
    "subcategory": 1,
    "productName": "Energy-efficient refrigerator",
    "manufacturer": "EcoTech",
    "country": "Germany",
    "price": 899,
    "description": "Energy-efficient appliance suitable for refrigeration needs. EcoTech presents the Energy Storage Unit 2000 with a capacity of 23.5 kWh, ideal for powering eco-friendly refrigerators.",
    "img": "./images/products/energy-efficient-products.jpg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "65678157776eddc6c35c0732",
    "category": 4,
    "subcategory": 1,
    "productName": "HeatMaster Pro 3",
    "manufacturer": "EcoHeat Solutions",
    "country": "United States",
    "price": 1299.99,
    "description": "Upgrade to the HeatMaster Pro, an eco-friendly and high-efficiency boiler by EcoHeat Solutions. With cutting-edge heating technology and a robust design, this boiler guarantees reliable warmth for your home while minimizing environmental impact.",
    "img": "./images/products/homeEf2.jpg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "65678157776eddc6c35c0734",
    "category": 4,
    "subcategory": 1,
    "productName": "HeatMaster Pro 2",
    "manufacturer": "EcoHeat Solutions",
    "country": "United States",
    "price": 1299.99,
    "description": "Upgrade to the HeatMaster Pro, an eco-friendly and high-efficiency boiler by EcoHeat Solutions. With cutting-edge heating technology and a robust design, this boiler guarantees reliable warmth for your home while minimizing environmental impact.",
    "img": "./images/products/homeEf3.jpg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "65678157776eddc6c35c0736",
    "category": 4,
    "subcategory": 1,
    "productName": "EcoKettle Plus",
    "manufacturer": "RenewableCo",
    "country": "Canada",
    "price": 899.99,
    "description": "RenewableCo introduces the EcoKettle Plus, an energy-efficient solution for boiling water. With advanced heating technology and a sleek design, this kettle brings you boiling water quickly and efficiently while minimizing energy consumption.",
    "img": "./images/products/homeEf4.jpg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "65678157776eddc6c35c073a",
    "category": 5,
    "subcategory": 1,
    "productName": "EcoWind X-1500",
    "manufacturer": "RenewableTech",
    "country": "Finland",
    "price": 1799.99,
    "description": "RenewableTech proudly presents the EcoWind X-1500, a high-capacity wind turbine designed for sustainable energy generation. With an impressive power output and cutting-edge technology, this wind turbine ensures efficient and eco-friendly electricity production for your renewable energy needs.",
    "img": "./images/products/turbine13.jpg",
    "discount": 0.3,
    "__v": 0
  },
  {
    "_id": "65678157776eddc6c35c073c",
    "category": 5,
    "subcategory": 1,
    "productName": "EcoWind Pro-2000",
    "manufacturer": "ABB",
    "country": "Finland",
    "price": 2599.99,
    "description": "Introducing the EcoWind Pro-2000 by ABB, a cutting-edge wind turbine for efficient and sustainable energy generation. With an enhanced Powerporter 11.0 system and an increased energy capacity of 13.6kWh, this turbine is designed to maximize your renewable energy output.",
    "img": "./images/products/turbine14.jpg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "65678157776eddc6c35c073e",
    "category": 5,
    "subcategory": 1,
    "productName": "EcoWind Pro-3000",
    "manufacturer": "ABB",
    "country": "Finland",
    "price": 2999.99,
    "description": "Discover the EcoWind Pro-3000 by ABB, an advanced wind turbine engineered for optimal energy production. Featuring the Powerporter 11.0 system with an impressive energy capacity of 14.6kWh, this turbine is your key to sustainable and high-performance renewable energy.",
    "img": "./images/products/turbine15.jpg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "65678157776eddc6c35c0740",
    "category": 5,
    "subcategory": 1,
    "productName": "EcoWind Ultra-4000",
    "manufacturer": "ABB",
    "country": "Finland",
    "price": 3499.99,
    "description": "Introducing the EcoWind Ultra-4000 by ABB, a state-of-the-art wind turbine designed for maximum energy efficiency. Equipped with the Powerporter 11.0 system and an impressive energy capacity of 16.6kWh, this turbine sets a new standard for sustainable and high-yield renewable energy production.",
    "img": "./images/products/turbine16.jpg",
    "discount": 0.5,
    "__v": 0
  },
  {
    "_id": "65678158776eddc6c35c0750",
    "category": 6,
    "subcategory": 1,
    "productName": "Inverter 11",
    "manufacturer": "RenewableCo",
    "country": "Canada",
    "price": 1099,
    "description": "RenewableCo presents the RenewaCharge XE-1200, an energy-efficient solution for powering appliances like pumps. With a storage capacity of 26.5 kWh, it ensures reliable and eco-friendly pump operation.",
    "img": "./images/products/inverter.jpg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "65678158776eddc6c35c0752",
    "category": 6,
    "subcategory": 1,
    "productName": "Inverter 21",
    "manufacturer": "EcoInnovate",
    "country": "Australia",
    "price": 1699,
    "description": "Upgrade to the GreenPower Ultra 4000, an energy-efficient appliance designed for sustainable living. With a capacity of 30.2 kWh, it is suitable for powering energy-efficient refrigerators and other household appliances.",
    "img": "./images/products/inverter.jpg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "65678158776eddc6c35c0754",
    "category": 6,
    "subcategory": 1,
    "productName": "Inverter 31",
    "manufacturer": "ABB",
    "country": "Finland",
    "price": 133,
    "description": "Powerporter 11.0 Energy Capacity: 11.6kWh",
    "img": "./images/products/inverter.jpg",
    "discount": 0.3,
    "__v": 0
  },
  {
    "_id": "65678158776eddc6c35c0756",
    "category": 6,
    "subcategory": 1,
    "productName": "Inverter 41",
    "manufacturer": "ABB",
    "country": "Finland",
    "price": 233,
    "description": "Powerporter 11.0 Energy Capacity: 13.6kWh",
    "img": "./images/products/inverter.jpg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "65678158776eddc6c35c0758",
    "category": 6,
    "subcategory": 1,
    "productName": "Inverter 51",
    "manufacturer": "ABB",
    "country": "Finland",
    "price": 533,
    "description": "Powerporter 11.0 Energy Capacity: 14.6kWh",
    "img": "./images/products/inverter.jpg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "65678158776eddc6c35c075a",
    "category": 6,
    "subcategory": 1,
    "productName": "Inverter 61",
    "manufacturer": "ABB",
    "country": "Finland",
    "price": 433,
    "description": "Powerporter 11.0 Energy Capacity: 16.6kWh",
    "img": "./images/products/inverter.jpg",
    "discount": 0.5,
    "__v": 0
  },
  {
    "_id": "65678158776eddc6c35c075c",
    "category": 6,
    "subcategory": 1,
    "productName": "Inverter 71",
    "manufacturer": "ABB",
    "country": "Finland",
    "price": 733,
    "description": "Powerporter 11.0 Energy Capacity: 20.6kWh",
    "img": "./images/products/inverter.jpg",
    "discount": 0.1,
    "__v": 0
  },
  {
    "_id": "65678158776eddc6c35c075e",
    "category": 6,
    "subcategory": 1,
    "productName": "Inverter 81",
    "manufacturer": "ABB",
    "country": "Finland",
    "price": 733,
    "description": "Powerporter 11.0 Energy Capacity: 19.6kWh",
    "img": "./images/products/inverter.jpg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "65678158776eddc6c35c0760",
    "category": 6,
    "subcategory": 1,
    "productName": "Inverter 91",
    "manufacturer": "ABB",
    "country": "Finland",
    "price": 533,
    "description": "Powerporter 11.0 Energy Capacity: 19.6kWh",
    "img": "./images/products/inverter.jpg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "65678158776eddc6c35c0762",
    "category": 6,
    "subcategory": 1,
    "productName": "Inverter 10",
    "manufacturer": "ABB",
    "country": "Finland",
    "price": 1033,
    "description": "Powerporter 11.0 Energy Capacity: 22.6kWh",
    "img": "./images/products/inverter.jpg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "65678158776eddc6c35c0764",
    "category": 6,
    "subcategory": 1,
    "productName": "Inverter 111",
    "manufacturer": "EcoTech",
    "country": "Germany",
    "price": 899,
    "description": "Energy-efficient appliance suitable for refrigeration needs. EcoTech presents the Energy Storage Unit 2000 with a capacity of 23.5 kWh, ideal for powering eco-friendly refrigerators.",
    "img": "./images/products/inverter.jpg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "65678158776eddc6c35c0766",
    "category": 6,
    "subcategory": 1,
    "productName": "Inverter 121",
    "manufacturer": "GreenEnergy",
    "country": "Sweden",
    "price": 1299,
    "description": "Upgrade your entertainment setup with this energy-efficient appliance. The PowerCell XR-500, manufactured by GreenEnergy, offers high-capacity energy storage of 25.8 kWh, perfect for powering modern televisions.",
    "img": "./images/products/inverter.jpg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "65678158776eddc6c35c0768",
    "category": 6,
    "subcategory": 1,
    "productName": "Inverter 131",
    "manufacturer": "SustainableTech",
    "country": "United States",
    "price": 1499,
    "description": "SustainableTech introduces the EcoPower Pro 3000, an energy-efficient appliance designed for household needs. With a storage capacity of 28.4 kWh, it is suitable for powering energy-efficient refrigerators.",
    "img": "./images/products/inverter.jpg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "65678158776eddc6c35c076a",
    "category": 6,
    "subcategory": 1,
    "productName": "Inverter 141",
    "manufacturer": "RenewableCo",
    "country": "Canada",
    "price": 1099,
    "description": "RenewableCo presents the RenewaCharge XE-1200, an energy-efficient solution for powering appliances like pumps. With a storage capacity of 26.5 kWh, it ensures reliable and eco-friendly pump operation.",
    "img": "./images/products/inverter.jpg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "65678158776eddc6c35c076c",
    "category": 6,
    "subcategory": 1,
    "productName": "Inverter 151",
    "manufacturer": "EcoInnovate",
    "country": "Australia",
    "price": 1699,
    "description": "Upgrade to the GreenPower Ultra 4000, an energy-efficient appliance designed for sustainable living. With a capacity of 30.2 kWh, it is suitable for powering energy-efficient refrigerators and other household appliances.",
    "img": "./images/products/inverter.jpg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "6575d0770a922f8981f1f15a",
    "category": 2,
    "subcategory": 2,
    "productName": "Polycristalline Panel 1",
    "manufacturer": "Solar Power Inc.",
    "country": "China",
    "price": 299,
    "description": "High-efficiency solar panel for residential and commercial use.",
    "img": "./images/products/pollycristalline.png",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "6575d0770a922f8981f1f15c",
    "category": 2,
    "subcategory": 2,
    "productName": "Polycristalline Panel 2",
    "manufacturer": "Sunergy",
    "country": "USA",
    "price": 350,
    "description": "Premium solar panel with advanced photovoltaic technology.",
    "img": "./images/products/pollycristalline.png",
    "discount": 0.2,
    "__v": 0
  },
  {
    "_id": "6575d0770a922f8981f1f15e",
    "category": 2,
    "subcategory": 2,
    "productName": "Polycristalline Panel 3",
    "manufacturer": "GreenEco",
    "country": "Germany",
    "price": 400,
    "description": "Eco-friendly solar panel for sustainable energy production.",
    "img": "./images/products/pollycristalline.png",
    "discount": 0.1,
    "__v": 0
  },
  {
    "_id": "6575d0770a922f8981f1f160",
    "category": 2,
    "subcategory": 2,
    "productName": "Polycristalline Panel 4",
    "manufacturer": "Solar Power Inc.",
    "country": "China",
    "price": 299,
    "description": "High-efficiency solar panel for residential and commercial use.",
    "img": "./images/products/pollycristalline.png",
    "discount": 0.15,
    "__v": 0
  },
  {
    "_id": "6575d0770a922f8981f1f162",
    "category": 2,
    "subcategory": 2,
    "productName": "Polycristalline Panel 5",
    "manufacturer": "Sunergy",
    "country": "USA",
    "price": 350,
    "description": "Premium solar panel with advanced photovoltaic technology.",
    "img": "./images/products/pollycristalline.png",
    "discount": 0.25,
    "__v": 0
  },
  {
    "_id": "6575d0770a922f8981f1f164",
    "category": 2,
    "subcategory": 2,
    "productName": "Polycristalline Panel 6",
    "manufacturer": "GreenEco",
    "country": "Germany",
    "price": 400,
    "description": "Eco-friendly solar panel for sustainable energy production.",
    "img": "./images/products/pollycristalline.png",
    "discount": 0.3,
    "__v": 0
  },
  {
    "_id": "6575d0770a922f8981f1f166",
    "category": 2,
    "subcategory": 3,
    "productName": "Thin-film Solar Panel 7",
    "manufacturer": "Solar Power Inc.",
    "country": "China",
    "price": 299,
    "description": "High-efficiency solar panel for residential and commercial use.",
    "img": "./images/products/thin-film-solar.png",
    "discount": 0.1,
    "__v": 0
  },
  {
    "_id": "6575d0770a922f8981f1f168",
    "category": 2,
    "subcategory": 3,
    "productName": "Thin-film Panel 8",
    "manufacturer": "Sunergy",
    "country": "USA",
    "price": 350,
    "description": "Premium solar panel with advanced photovoltaic technology.",
    "img": "./images/products/thin-film-solar.png",
    "discount": 0.2,
    "__v": 0
  },
  {
    "_id": "6575d0780a922f8981f1f16a",
    "category": 2,
    "subcategory": 3,
    "productName": "Thin-film Panel 9",
    "manufacturer": "GreenEco",
    "country": "Germany",
    "price": 400,
    "description": "Eco-friendly solar panel for sustainable energy production.",
    "img": "./images/products/thin-film-solar.png",
    "discount": 0.15,
    "__v": 0
  },
  {
    "_id": "6575d0780a922f8981f1f16c",
    "category": 2,
    "subcategory": 3,
    "productName": "Thin-film Panel 10",
    "manufacturer": "Solar Power Inc.",
    "country": "China",
    "price": 299,
    "description": "High-efficiency solar panel for residential and commercial use.",
    "img": "./images/products/thin-film-solar.png",
    "discount": 0.25,
    "__v": 0
  },
  {
    "_id": "6575d0780a922f8981f1f16e",
    "category": 2,
    "subcategory": 3,
    "productName": "Thin-film Panel 11",
    "manufacturer": "Sunergy",
    "country": "USA",
    "price": 350,
    "description": "Premium solar panel with advanced photovoltaic technology.",
    "img": "./images/products/thin-film-solar.png",
    "discount": 0.3,
    "__v": 0
  },
  {
    "_id": "6575d99864db67c39d8d2f87",
    "category": 3,
    "subcategory": 2,
    "productName": "Flywheel 1",
    "manufacturer": "Solar Power Inc.",
    "country": "China",
    "price": 1299,
    "description": "High-efficiency solar panel for residential and commercial use.",
    "img": "./images/products/flywheel.jpeg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "6575d99864db67c39d8d2f89",
    "category": 3,
    "subcategory": 2,
    "productName": "Flywheel 2",
    "manufacturer": "Sunergy",
    "country": "USA",
    "price": 1350,
    "description": "Premium solar panel with advanced photovoltaic technology.",
    "img": "./images/products/flywheel.jpeg",
    "discount": 0.2,
    "__v": 0
  },
  {
    "_id": "6575d99864db67c39d8d2f8b",
    "category": 3,
    "subcategory": 2,
    "productName": "Flywheel 3",
    "manufacturer": "GreenEco",
    "country": "Germany",
    "price": 1400,
    "description": "Eco-friendly solar panel for sustainable energy production.",
    "img": "./images/products/flywheel.jpeg",
    "discount": 0.1,
    "__v": 0
  },
  {
    "_id": "6575d99864db67c39d8d2f8d",
    "category": 3,
    "subcategory": 2,
    "productName": "Flywheel 4",
    "manufacturer": "Solar Power Inc.",
    "country": "China",
    "price": 1299,
    "description": "High-efficiency solar panel for residential and commercial use.",
    "img": "./images/products/flywheel.jpeg",
    "discount": 0.15,
    "__v": 0
  },
  {
    "_id": "6575d99864db67c39d8d2f8f",
    "category": 3,
    "subcategory": 2,
    "productName": "Flywheel 5",
    "manufacturer": "Sunergy",
    "country": "USA",
    "price": 1350,
    "description": "Premium solar panel with advanced photovoltaic technology.",
    "img": "./images/products/flywheel.jpeg",
    "discount": 0.25,
    "__v": 0
  },
  {
    "_id": "6575d99864db67c39d8d2f91",
    "category": 3,
    "subcategory": 2,
    "productName": "Flywheel 6",
    "manufacturer": "GreenEco",
    "country": "Germany",
    "price": 4000,
    "description": "Eco-friendly solar panel for sustainable energy production.",
    "img": "./images/products/flywheel.jpeg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "6575d99964db67c39d8d2f93",
    "category": 3,
    "subcategory": 3,
    "productName": "Thermal storage 7",
    "manufacturer": "Solar Power Inc.",
    "country": "China",
    "price": 2990,
    "description": "High-efficiency solar panel for residential and commercial use.",
    "img": "./images/products/thermal-storage.jpeg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "6575d99964db67c39d8d2f95",
    "category": 3,
    "subcategory": 3,
    "productName": "Thermal storage 8",
    "manufacturer": "Sunergy",
    "country": "USA",
    "price": 3500,
    "description": "Premium solar panel with advanced photovoltaic technology.",
    "img": "./images/products/thermal-storage.jpeg",
    "discount": 0.2,
    "__v": 0
  },
  {
    "_id": "6575d99964db67c39d8d2f99",
    "category": 3,
    "subcategory": 3,
    "productName": "Thermal storage 10",
    "manufacturer": "Solar Power Inc.",
    "country": "China",
    "price": 2990,
    "description": "High-efficiency solar panel for residential and commercial use.",
    "img": "./images/products/thermal-storage.jpeg",
    "discount": 0.1,
    "__v": 0
  },
  {
    "_id": "6575d99964db67c39d8d2f9b",
    "category": 3,
    "subcategory": 3,
    "productName": "Thermal storage 11",
    "manufacturer": "Sunergy",
    "country": "USA",
    "price": 3500,
    "description": "Premium solar panel with advanced photovoltaic technology.",
    "img": "./images/products/thermal-storage.jpeg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "6575e771540f553d14f63ad4",
    "category": 1,
    "subcategory": 2,
    "productName": "Public charge 1",
    "manufacturer": "Solar Power Inc.",
    "country": "China",
    "price": 199,
    "description": "High-efficiency solar panel for residential and commercial use.",
    "img": "./images/products/public-charging.png",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "6575e771540f553d14f63ad6",
    "category": 1,
    "subcategory": 2,
    "productName": "Public charge 2",
    "manufacturer": "Sunergy",
    "country": "USA",
    "price": 350,
    "description": "Premium solar panel with advanced photovoltaic technology.",
    "img": "./images/products/public-charging.png",
    "discount": 0.2,
    "__v": 0
  },
  {
    "_id": "6575e771540f553d14f63ad8",
    "category": 1,
    "subcategory": 2,
    "productName": "Public charge 3",
    "manufacturer": "GreenEco",
    "country": "Germany",
    "price": 400,
    "description": "Eco-friendly solar panel for sustainable energy production.",
    "img": "./images/products/public-charging.png",
    "discount": 0.1,
    "__v": 0
  },
  {
    "_id": "6575e771540f553d14f63ada",
    "category": 1,
    "subcategory": 2,
    "productName": "Public charge 4",
    "manufacturer": "Solar Power Inc.",
    "country": "China",
    "price": 299,
    "description": "High-efficiency solar panel for residential and commercial use.",
    "img": "./images/products/public-charging.png",
    "discount": 0.15,
    "__v": 0
  },
  {
    "_id": "6575e771540f553d14f63adc",
    "category": 1,
    "subcategory": 2,
    "productName": "Public charge 5",
    "manufacturer": "Sunergy",
    "country": "USA",
    "price": 130,
    "description": "Premium solar panel with advanced photovoltaic technology.",
    "img": "./images/products/public-charging.png",
    "discount": 0.25,
    "__v": 0
  },
  {
    "_id": "6575e771540f553d14f63ade",
    "category": 1,
    "subcategory": 2,
    "productName": "Public charge 6",
    "manufacturer": "GreenEco",
    "country": "Germany",
    "price": 400,
    "description": "Eco-friendly solar panel for sustainable energy production.",
    "img": "./images/products/public-charging.png",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "6575e771540f553d14f63ae0",
    "category": 1,
    "subcategory": 3,
    "productName": "Super charging 7",
    "manufacturer": "Solar Power Inc.",
    "country": "China",
    "price": 290,
    "description": "High-efficiency solar panel for residential and commercial use.",
    "img": "./images/products/super-charge.jpg",
    "discount": 0,
    "__v": 0
  },
  {
    "_id": "6575e771540f553d14f63ae2",
    "category": 1,
    "subcategory": 3,
    "productName": "Super charging 8",
    "manufacturer": "Sunergy",
    "country": "USA",
    "price": 3500,
    "description": "Premium solar panel with advanced photovoltaic technology.",
    "img": "./images/products/super-charge.jpg",
    "discount": 0.2,
    "__v": 0
  },
  {
    "_id": "6575e771540f553d14f63ae4",
    "category": 1,
    "subcategory": 3,
    "productName": "Super charging 9",
    "manufacturer": "GreenEco",
    "country": "Germany",
    "price": 4000,
    "description": "Eco-friendly solar panel for sustainable energy production.",
    "img": "./images/products/super-charge.jpg",
    "discount": 0.15,
    "__v": 0
  },
  {
    "_id": "6575e771540f553d14f63ae6",
    "category": 1,
    "subcategory": 3,
    "productName": "Super charging 10",
    "manufacturer": "Solar Power Inc.",
    "country": "China",
    "price": 2990,
    "description": "High-efficiency solar panel for residential and commercial use.",
    "img": "./images/products/super-charge.jpg",
    "discount": 0.1,
    "__v": 0
  },
  {
    "_id": "6575e771540f553d14f63ae8",
    "category": 1,
    "subcategory": 3,
    "productName": "Super charging 11",
    "manufacturer": "Sunergy",
    "country": "USA",
    "price": 3500,
    "description": "Premium solar panel with advanced photovoltaic technology.",
    "img": "./images/products/super-charge.jpg",
    "discount": 0,
    "__v": 0
  }
]
